import type { Metadata } from "next";
import { Inter, Staatliches} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const staatliches = Staatliches({ 
  weight: "400",
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={staatliches.className + " flex flex-col items-center min-h-screen border bg-[url('/background.png')] bg-cover"}>
        <Navbar />
        <div className="flex flex-col container">
          {children}
        </div>
      </body>
    </html>
  );
}
